config/routes.rb
Rails.application.routes.draw do
  resources :galleries
  get 'welcome/index'
  get 'welcome/about_us'
  get 'welcome/contact_us'
  get 'welcome/gallery'
  # resources :subdomains
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'welcome#index'
  # match '/', to: 'subdomains#index', constraints: { subdomain: 'your-custom-domain-name' }, via: [:get, :post, :put, :patch, :delete]
  # constraints(SubdomainRoutes) do
  #   resources :subdomains
  #   root 'welcome#index'
  # end
  
  # constraints(!SubdomainRoutes) do
  #   resources :subdomains do
  #     resources :posts
  #   end
  #   root 'subdomains#show'
  # end
  # match '/', to: 'subdomains#show', constraints: { subdomain: /.+/ }, via: [:get, :post, :put, :patch, :delete]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # skip_before_action :ensure_subdomain

  def index
    @subdomains = Subdomain.all
  end
  def contact_us
  	
  end
  def about_us
  	
  end
  def gallery
  	
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_footer.html.erb
<!--/newsletter-->
    <footer class="newsletter_right pymd-5 py-4" id="footer">
        <div class="container">
            <div class="inner-sec py-md-5 py-3">
                <div class="row mb-md-4 mb-md-3">
          <div class="col-lg-3 col-md-6 social-info text-left">
                       <h3 class="tittle1 foot mb-md-5 mb-4 text-white">Get in touch</h3>
            <p>0926k 4th block building,king Avenue, </p>
            <p class="my-2"> New York City,USA</p>
            <p class="phone">phone: +0444 555 6789</p>
            <p class="phone my-2">Fax: +0444 555 6789</p>
            <p class="phone">Mail:
              <a href="mailto:info@example.com">info@example.com</a>
            </p>

                    </div>
          <div class="col-lg-3 col-md-6 social-info text-left">
           <h3 class="tittle1 foot mb-md-5 mb-4 text-white">About Us</h3>
                       <p>Curabitur non nulla sit amet nislinit tempus convallis quis ac lectus. lac inia eget consectetur sed, convallis at tellus.
            Nulla porttitor accumsana tincidunt. Vestibulum ante ipsum primis tempus convallis.</p>

                    </div>
                    <div class="col-lg-6 col-md-12 n-right tex-left">
                        <h3 class="tittle1 foot mb-md-5 mb-4 text-white">Subscribe our Newsletter</h3>
                        <form action="#" method="post">
                            <div class="form-group d-flex">
                                <input class="form-control" type="email" name="Email" placeholder=" Email Address" required="">
                                <button class="form-control submit text-uppercase" type="submit ">Subscribe</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </footer>
  <div class="copyright py-3">
    <div class="container">
      <div class="row">
        <div class="col-md-8">      
          <p class="copy-right mt-2">© 2019 Wedding Planner. All Rights Reserved.
          </p>
        </div>
        <div class="col-md-4">
          <ul class="social-icons scial justify-content-end">
            <li class="mr-1"><a href="#"><span class="fa fa-facebook"></span></a></li>
            <li class="mx-1"><a href="#"><span class="fa fa-twitter"></span></a></li>
            <li class="mx-1"><a href="#"><span class="fa fa-google-plus"></span></a></li>
            <li class="mx-1"><a href="#"><span class="fa fa-linkedin"></span></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
    <!--//newsletter-->

app/views/welcome/_header.html.erb
  <header>  
  <nav class="mnu navbar-light">
            <div class="logo" id="logo">
                <h1><a href="index.html">W-Planner</a></h1>
            </div>
        <label for="drop" class="toggle"><span class="fa fa-bars"></span></label>
                <input type="checkbox" id="drop">
                    <ul class="menu">
                        <li><%= link_to "Home", welcome_index_path, class: "link-color" %></li>
                        <li><%= link_to "About", welcome_about_us_path, class: "link-color"%></li>
                        <li><%= link_to "Gallery", welcome_gallery_path, class: "link-color"%></li>
                        <li><%= link_to "Contact Us", welcome_contact_us_path, class: "link-color"%></li>
                    </ul>
    </nav>
</header>

app/views/welcome/about_us.html.erb
<!DOCTYPE html>
<html lang="zxx">

<head>
    <title>Wedding Planner Wedding Category Flat Bootstrap Responsive website Template | About </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8" />
    <meta name="keywords" content="Wedding Planner Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
	SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
</head>

<body>
    <!-- banner -->
    <div class="inner-banner">
<%= render 'header'%>
       
    </div>
	<ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="index.html">Home</a>
        </li>
        <li class="breadcrumb-item active">About</li>
    </ol>
	 <!-- //banner-text -->
	 <section class="banner_bottom1 py-md-5">
		<div class="container py-4 mt-2">
			<h3 class="heading-voyileinfo text-center">About  <span>Us</span></h3>
			<div class="inner_sec_info_voyree_voyile mt-md-5 pt-3">
				<div class="row help_full">
					<div class="col-lg-6 banner_bottom_grid help">
						<img src="images/g1.jpg" alt=" " class="img-fluid">
					</div>
					<div class="col-lg-6 banner_bottom_left1">
						<h4>Lorem Ipsum convallis diam</h4>
						<p>Pellentesque convallis diam consequat magna vulputate malesuada. Cras a ornare elit. Nulla viverra pharetra sem, eget
							pulvinar neque pharetra ac.</p>
						<p>Lorem Ipsum convallis diam consequat magna vulputate malesuada. Cras a ornare elit. Nulla viverra pharetra sem, eget
							pulvinar neque pharetra ac.Nullal condimentum interdum vel eget enim. Curabitur mattis orci sed le. Nullal condimentum interdum vel eget enim. Curabitur mattis orci sed le.</p>
						</div>
				</div>
			</div>
		</div>
	</section>

	<!-- choose -->
	<section class="choose py-5">
		<div class="container py-md-4 mt-md-3"> 
			<div class="row inner_voy3l_voyile_grids-1 ">
				<div class="col-lg-6 voy3layouts_choose_left_grid1">
					<div class="choose_top">
						<h4 class="mb-3 mt-3 text-white">Feel Free to Contact Our Agents Directly</h4>
						<p class="text-white">Nulla pellentesque mi non laoreet eleifend. Integer porttitor mollisar lorem, at molestie arcu pulvinar ut. Proin ac fermentum est. Cras mi ipsum, consectetur ac ipsum in, egestas vestibulum tellus.Proin ac fermentum est. Cras mi ipsum, consectetur ac ipsum in, egestas vestibulum tellus.</p>
						<a href="services.html" class="btn btn-primary mt-3">Read More</a>
					</div>
				</div>
				<div class="col-lg-6 voy3layouts_choose_left_grid2">
					<div class="row">
						<div class="col-md-6 voy3l_choose_bottom1 mt-3 pt-md-4">
							<div class="choose_bottom_top">
                                <span class="fa fa-gift mb-2"></span>
                                <h5 class="card-title text-uppercase my-3">Weddings</h5>
                                <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing.
                                </p>
                            </div>
						</div>
						<div class="col-md-6 voy3l_choose_bottom2">
							<div class="choose_bottom_top">
                                <span class="fa fa-cutlery mb-2"></span>
                                <h5 class="card-title text-uppercase my-3">Parties</h5>
                                <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing.
                                </p>
                            </div>
						</div>
						<div class="col-md-6 voy3l_choose_bottom3 mt-3 pt-md-4">
							<div class="choose_bottom_top">
                                <span class="fa fa-music mb-2"></span>
                                <h5 class="card-title text-uppercase my-3">Entertainment</h5>
                                <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing.
                                </p>
                            </div>
						</div>
						<div class="col-md-6 voy3l_choose_bottom4">
							<div class="choose_bottom_top">
                                <span class="fa fa-glass mb-2"></span>
                                <h5 class="card-title text-uppercase my-3">Celebrations</h5>
                                <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing.
                                </p>
                            </div>
						</div>
					</div>
				</div>
			</div>
	</div>   
</section>
<!-- //choose -->
	<!-- team -->
	<section class="team py-md-5 py-4">
        <div class="container py-lg-5">
            <h2 class="heading-voyileinfo text-center  mb-4">Wedding Planners</h2>
			<div class="row inner-sec-voy3layouts-voyileinfo pt-md-5">
				<div class="col-md-3 col-sm-6 team-grids aos-init" data-aos="flip-left">
					<img src="images/t4.jpg" class="img-fluid" alt="">
					<div class="team-info">
						<div class="caption">
							<h4>John Doe</h4>
							<h6>Lorem
								</h6><h6>
						</h6></div>
						<div class="social-icons-section">
							<a class="fac" href="#">
								<span class="fa fa-facebook"></span>
							</a>
							<a class="twitter" href="#">
								<span class="fa fa-twitter"></span>
							</a>
							<a class="pinterest" href="#">
								<span class="fa fa-pinterest"></span>
							</a>

						</div>

					</div>
				</div>
				<div class="col-md-3 col-sm-6 team-grids aos-init" data-aos="flip-right">
					<img src="images/t2.jpg" class="img-fluid" alt="">
					<div class="team-info">
						<div class="caption">
							<h4>Alina Smith</h4>
							<h6>Lorem</h6>
						</div>
						<div class="social-icons-section">
							<a class="fac" href="#">
								<span class="fa fa-facebook"></span>
							</a>
							<a class="twitter" href="#">
								<span class="fa fa-twitter"></span>
							</a>
							<a class="pinterest" href="#">
								<span class="fa fa-pinterest"></span>
							</a>

						</div>
					</div>
				</div>
				<div class="col-md-3 col-sm-6 team-grids aos-init" data-aos="flip-left">
					<img src="images/t3.jpg" class="img-fluid" alt="">
					<div class="team-info">
						<div class="caption">
							<h4>Adam Lobster</h4>
							<h6>Lorem</h6>
						</div>
						<div class="social-icons-section">
							<a class="fac" href="#">
								<span class="fa fa-facebook"></span>
							</a>
							<a class="twitter" href="#">
								<span class="fa fa-twitter"></span>
							</a>
							<a class="pinterest" href="#">
								<span class="fa fa-pinterest"></span>
							</a>

						</div>
					</div>
				</div>
				<div class="col-md-3 col-sm-6 team-grids aos-init" data-aos="flip-right">
					<img src="images/t1.jpg" class="img-fluid" alt="">
					<div class="team-info">
						<div class="caption">
							<h4>Chris Woakes </h4>
							<h6>Lorem</h6>
						</div>
						<div class="social-icons-section">
							<a class="fac" href="#">
								<span class="fa fa-facebook"></span>
							</a>
							<a class="twitter" href="#">
								<span class="fa fa-twitter"></span>
							</a>
							<a class="pinterest" href="#">
								<span class="fa fa-pinterest"></span>
							</a>

						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- //team -->
	<%= render 'footer' %>
</body>
</html>

app/views/welcome/contact_us.html.erb
<!DOCTYPE html>
<html lang="zxx">

<head>
    <title>Wedding Planner Wedding Category Flat Bootstrap Responsive website Template | Contact </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8" />
    <meta name="keywords" content="Wedding Planner Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
	SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!-- Custom Theme files -->
    <link href="css/bootstrap.css" type="text/css" rel="stylesheet" media="all">
    <link href="css/style.css" type="text/css" rel="stylesheet" media="all">
	<!-- font-awesome icons -->
    <link href="css/fontawesome-all.min.css" rel="stylesheet">
	<!-- //Custom Theme files -->
     <!-- online-fonts -->
	<link href="//fonts.googleapis.com/css?family=Roboto:100i,400,500,700" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Josefin+Sans:300,400,600,700" rel="stylesheet">
	<!-- //online-fonts -->
</head>
<body>
    <!-- banner -->
    <div class="inner-banner">
       <!-- header -->
    <%= render 'header'%>       
    </div>
	 <!-- //banner-text -->
	   <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="index.html">Home</a>
        </li>
        <li class="breadcrumb-item active">Contact</li>
    </ol>
    <!-- contact -->
    <section class="banner-bottom-voy3ls pt-lg-5 pt-md-3 pt-3">
        <div class="inner-sec-voyreelayouts pt-md-5 pt-md-3 pt-3">
			<h2 class="heading-voyileinfo text-center  mb-4">Get In Touch</h2>
			<div class="container pt-sm-5">
                <div class="address row mb-5">
                    <div class="col-lg-4 address-grid-voy3l">
                        <div class="row address-info">
                            <div class="col-3 address-left text-center">
                                <span class="fa fa-map"></span>
                            </div>
                            <div class="col-9 address-right text-left">
                                <h6 class="ad-info text-uppercase mb-2">Address</h6>
                                <p> California, USA

                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 address-grid-voy3l">
                        <div class="row address-info">
                            <div class="col-3 address-left text-center">
                                <span class="fa fa-envelope"></span>
                            </div>
                            <div class="col-9 address-right text-left">
                                <h6 class="ad-info text-uppercase mb-2">Email</h6>
                                <p>Email :
                                    <a href="mailto:example@email.com"> mail@example.com</a>
                                </p>
                            </div>

                        </div>
                    </div>
                    <div class="col-lg-4 address-grid-voy3l">
                        <div class="row address-info">
                            <div class="col-3 address-left text-center">
                                <span class="fa fa-mobile"></span>
                            </div>
                            <div class="col-9 address-right text-left">
                                <h6 class="ad-info text-uppercase mb-2">Phone</h6>
                                <p>+1 234 567 8901</p>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6 map">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d423286.27404345275!2d-118.69191921441556!3d34.02016130939095!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2c75ddc27da13%3A0xe22fdf6f254608f4!2sLos+Angeles%2C+CA%2C+USA!5e0!3m2!1sen!2sin!4v1522474296007" allowfullscreen></iframe>

                    </div>
                    <div class="col-md-6 main_grid_contact">
                        <div class="form">
                            <h4 class="mb-4 text-left">Send us a message</h4>
                            <form action="#" method="post">
                                <div class="form-group">
                                    <label class="my-2">Name</label>
                                    <input class="form-control" type="text" name="Name" placeholder="" required="">
                                </div>
                                <div class="form-group">
                                    <label>Email</label>
                                    <input class="form-control" type="email" name="Email" placeholder="" required="">
                                </div>
                                <div class="form-group">
                                    <label>Message</label>
                                    <textarea id="textarea" placeholder=""></textarea>
                                </div>
                                <div class="input-group1">
                                    <button class="form-control" type="submit">Submit</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- //contact -->
    <%= render 'footer' %>
</body>
</html>

app/views/welcome/gallery.html.erb
<!DOCTYPE html>
<html lang="zxx">

<head>
    <title>Wedding Planner Wedding Category Flat Bootstrap Responsive website Template | Gallery </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8" />
    <meta name="keywords" content="Wedding Planner Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
	SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
</head>

<body>
    <!-- banner -->
    <div class="inner-banner">
    <%= render 'header' %>       
    </div>
	 <!-- //banner-text -->
	 	<ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="index.html">Home</a>
        </li>
        <li class="breadcrumb-item active">Gallery</li>
    </ol>
	<!--Gallery-->
		<div class="ga-top">
	<section class="gallery py-lg-5 editContent">
	<div class="container">
	<div class="title-section pt-5 text-center">
    
			  <h2 class="heading-voyileinfo text-center  mb-4">Our Gallery</h2>
 </div>
	 </div>
	</section>
	 <div class="gal-content">
		<div class="container py-5">
            
			<div class="row voyile_gallery_grids voy3-voyile demo">
				<div class="col-md-4 gal-sec">
					<div class="gallery-grid1">
						<a href="#gal1">
						<img src="../assets/g1.jpg" alt=" " class="img-fluid" />
						
						</a>
					</div>
					<div class="gallery-grid1">
						<a href="#gal2">
						<img src="../assets/g2.jpg" alt=" " class="img-fluid" />
						
						</a>
					</div>
					<div class="gallery-grid1">
						<a href="#gal3">
						<img src="../assets/g3.jpg" alt=" " class="img-fluid" />
						
						</a>
					</div>
				</div>
				<div class="col-md-4 gal-sec">
					<div class="gallery-grid1">
						<a href="#gal4">
						<img src="../assets/g4.jpg" alt=" " class="img-fluid" />
						
						</a>
					</div>
					<div class="gallery-grid1">
						<a href="#gal5">
						<img src="../assets/g5.jpg" alt=" " class="img-fluid" />
						
						</a>
					</div>
					<div class="gallery-grid1">
						<a href="#gal6">
						<img src="../assets/g6.jpg" alt=" " class="img-fluid" />
						
						</a>
					</div>
				</div>
				<div class="col-md-4 gal-sec">
					<div class="gallery-grid1">
						<a href="#gal7">
						<img src="../assets/g7.jpg" alt=" " class="img-fluid" />
						
						</a>
					</div>
					<div class="gallery-grid1">
						<a href="#gal8">
						<img src="../assets/g8.jpg" alt=" " class="img-fluid" />
						
						</a>
					</div>
					<div class="gallery-grid1">
						<a href="#gal9">
						<img src="../assets/g9.jpg" alt=" " class="img-fluid" />
						
						</a>
					</div>
				</div>
			</div>
		</div>
		</div>
	 
	
	
	 <!-- popup-->
        <div id="gal1" class="pop-overlay animate">
            <div class="popup">
                <img src="../assets/g1.jpg" alt="Popup Image" class="img-fluid" />
                <p class="mt-4 editContent">Nulla viverra pharetra se, eget pulvinar neque pharetra ac int. placerat placerat dolor.</p>
                <a class="close" href="#gallery">&times;</a>
            </div>
        </div>
        <!-- //popup -->

        <!-- popup-->
        <div id="gal2" class="pop-overlay animate">
            <div class="popup">
                <img src="../assets/g2.jpg" alt="Popup Image" class="img-fluid" />
                <p class="mt-4 editContent">Nulla viverra pharetra se, eget pulvinar neque pharetra ac int. placerat placerat dolor.</p>
                <a class="close" href="#gallery">&times;</a>
            </div>
        </div>
        <!-- //popup -->
        <!-- popup-->
        <div id="gal3" class="pop-overlay animate">
            <div class="popup">
                <img src="../assets/g3.jpg" alt="Popup Image" class="img-fluid" />
                <p class="mt-4 editContent">Nulla viverra pharetra se, eget pulvinar neque pharetra ac int. placerat placerat dolor.</p>
                <a class="close" href="#gallery">&times;</a>
            </div>
        </div>
        <!-- //popup3 -->
        <!-- popup-->
        <div id="gal4" class="pop-overlay animate">
            <div class="popup">
                <img src="../assets/g4.jpg" alt="Popup Image" class="img-fluid" />
                <p class="mt-4 editContent">Nulla viverra pharetra se, eget pulvinar neque pharetra ac int. placerat placerat dolor.</p>
                <a class="close" href="#gallery">&times;</a>
            </div>
        </div>
        <!-- //popup -->
        <!-- popup-->
        <div id="gal5" class="pop-overlay animate">
            <div class="popup">
                <img src="../assets/g5.jpg" alt="Popup Image" class="img-fluid" />
                <p class="mt-4 editContent">Nulla viverra pharetra se, eget pulvinar neque pharetra ac int. placerat placerat dolor.</p>
                <a class="close" href="#gallery">&times;</a>
            </div>
        </div>
        <!-- //popup -->
        <!-- popup-->
        <div id="gal6" class="pop-overlay animate">
            <div class="popup">
                <img src="../assets/g6.jpg" alt="Popup Image" class="img-fluid" />
                <p class="mt-4 editContent">Nulla viverra pharetra se, eget pulvinar neque pharetra ac int. placerat placerat dolor.</p>
                <a class="close" href="#gallery">&times;</a>
            </div>
        </div>
        <!-- //popup -->
  <!-- popup-->
        <div id="gal7" class="pop-overlay animate">
            <div class="popup">
                <img src="../assets/g7.jpg" alt="Popup Image" class="img-fluid" />
                <p class="mt-4 editContent">Nulla viverra pharetra se, eget pulvinar neque pharetra ac int. placerat placerat dolor.</p>
                <a class="close" href="#gallery">&times;</a>
            </div>
        </div>
        <!-- //popup -->
		  <!-- popup-->
        <div id="gal8" class="pop-overlay animate">
            <div class="popup">
                <img src="../assets/g8.jpg" alt="Popup Image" class="img-fluid" />
                <p class="mt-4 editContent">Nulla viverra pharetra se, eget pulvinar neque pharetra ac int. placerat placerat dolor.</p>
                <a class="close" href="#gallery">&times;</a>
            </div>
        </div>
        <!-- //popup -->
		  <!-- popup-->
        <div id="gal9" class="pop-overlay animate">
            <div class="popup">
                <img src="../assets/g9.jpg" alt="Popup Image" class="img-fluid" />
                <p class="mt-4 editContent">Nulla viverra pharetra se, eget pulvinar neque pharetra ac int. placerat placerat dolor.</p>
                <a class="close" href="#gallery">&times;</a>
            </div>
        </div>
        <!-- //popup -->
	<!--//Gallery-->
	</div>
    <%= render 'footer' %>
</body>
</html>